### ISSUE TITLE
Use flag.Usage()

### ISSUE THREAD

**Issue by ebiiim** [takayukioda/pemstore#1]
https://github.com/takayukioda/pemstore/blob/a64cabcbdc5e0061ca8efc196490e80baa278e62/cmd/main.go#L47-L50

You can use `flag.Usage` and `flag.PrintDefaults` as below to print usage for parameters!

```go
	const usageFmt = "%s [-profile <profile>] <get / list / store>\n"
	flag.Usage = func() {
		fmt.Fprintf(os.Stderr, usageFmt, os.Args[0])
		flag.PrintDefaults()
	}

	if len(args) < 1 {
		flag.Usage()
		os.Exit(EXIT_ERR_KNOWN)
	}
```

```text
$ ./pemstore
./pemstore [-profile <profile>] <get / list / store>
  -force
        Do action forcefully; available for store and delete
  -mfa
        MFA enabled
  -profile string
        AWS profile to use
```

**Comment by takayukioda** [comment]
Oh wow, thanks! I totally forgot about the possibility of usage function...

Note to myself:
I also need to check if this usage function works for subcommand as well. Subcommand can be specified by `flag.NewFlagSet`
https://gobyexample.com/command-line-subcommands
