### ISSUE TITLE
Use errors.Is

### ISSUE THREAD

**Issue by Warashi** [takayukioda/pemstore#2]
https://github.com/takayukioda/pemstore/blob/a64cabcbdc5e0061ca8efc196490e80baa278e62/cmd/main.go#L37
godoc of os.IsNotExist has below message
> New code should use errors.Is(err, os.ErrNotExist).

ref: https://golang.org/pkg/os/#IsNotExist

https://github.com/takayukioda/pemstore/blob/a64cabcbdc5e0061ca8efc196490e80baa278e62/cmd/main.go#L59
There is os.IsExist, but its godoc has below message as same as os.IsNotExist.
> New code should use errors.Is(err, os.ErrExist).

ref: https://golang.org/pkg/os/#IsExist

**Comment by Warashi** [comment]
Oops, `!os.IsNotExist(err)` is not same as `os.IsExist(err)`.
please ignore latter messages

**Comment by takayukioda** [comment]
Thanks for the advice! Didn't noticed about preferred code.
