### ISSUE TITLE
Use PemStore interface

### ISSUE THREAD

**Issue by ebiiim** [takayukioda/pemstore#4]
https://github.com/takayukioda/pemstore/blob/a64cabcbdc5e0061ca8efc196490e80baa278e62/cmd/main.go#L52

You might want to do this as below to declare `store` as `PemStore`, instead of `ssmStore`.

```go
	var store pemstore.PemStore = pemstore.New(profile, *mfa, nil)
```

**Comment by takayukioda** [comment]
Ah, true! I'll update it right away 👍🏽
